# Generated by Django 5.0 on 2023-12-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
