# Generated by Django 5.0 on 2023-12-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_studentregister_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='joiningDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='mobile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='qualification',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
